name: CD

on: 
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:     # Allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15   # Add timeout to prevent hanging jobs

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0  # Fetch all history for proper versioning

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install graph-cli
          sudo apt update -y
          sudo apt install -y jq

      - name: Check script files
        id: check_scripts
        run: |
          if [ -f ./collect_data.sh ]; then
            echo "collect_script_exists=true" >> $GITHUB_OUTPUT
          else
            echo "collect_script_exists=false" >> $GITHUB_OUTPUT
          fi
          
          if [ -f ./build.sh ]; then
            echo "build_script_exists=true" >> $GITHUB_OUTPUT
          else
            echo "build_script_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Collect data
        if: steps.check_scripts.outputs.collect_script_exists == 'true'
        env:
          ACCESS_TOKEN: ${{ github.token }}
        run: bash ./collect_data.sh 65

      - name: Build
        if: steps.check_scripts.outputs.build_script_exists == 'true'
        run: bash ./build.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automatic update [skip ci]"
          commit_options: '--amend'
          push_options: '--force'
          file_pattern: '*.json *.md *.html *.svg *.css *.js'
          skip_dirty_check: false  # Only commit if there are changes
