# See https://github.com/lowlighter/metrics for documentation
# This workflow is scheduled to run daily, and also after each commit on master/main branch

name: Metrics
on:
  schedule:
    - cron: "0 16 * * *"  # Run daily at 16:00 UTC
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**.svg'  # Avoid infinite loops by ignoring changes to SVG files
      - '**.md'
  workflow_dispatch:  # Allow manual triggering

# Set the default permissions
permissions:
  contents: write
  pull-requests: write
  issues: write
  checks: write
  statuses: write

jobs:
  github-metrics-personal:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add timeout to prevent hanging jobs
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Docker
        uses: docker/setup-buildx-action@v3

      - name: 🦑 Personal metrics (left)
        id: metrics_left
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: header
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, vue, scala, c, c++, python, ejs
          plugin_languages_skipped: lowlighter
          plugin_languages_details: lines, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes
          plugin_languages_limit: 0
          plugin_topics: yes
          plugin_topics_limit: 0
          plugin_topics_mode: mastered
          plugin_notable: no
          plugin_notable_repositories: no
          plugin_people: yes
          plugin_people_limit: 24
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_discussions: no
          config_order: base.header, isocalendar, languages, notable, discussions, topics
          output_action: pull-request
          retries: 3  # Add retries for API rate limit issues
          retry_delay: 300  # Delay between retries in seconds

      - name: 🦑 Personal metrics (bottom 1)
        id: metrics_achievements
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.personal.achievements.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          output_action: pull-request
          retries: 3
          retry_delay: 300

      - name: 🦑 Personal metrics (bottom 2)
        id: metrics_sponsors
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.personal.sponsors.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_sponsors: yes
          output_action: pull-request-squash
          retries: 3
          retry_delay: 300
